* 1
<2013-07-16 二> 继续学习蓝牙模块的源码，尝试加入多媒体功能。由于没有蓝牙耳机等设备，下午开始看其他系统设置模块的代码。
<2013-07-17 三> 上午Accout模块，学习ConsoleKit，Accout等接口的使用。下午继续
<2013-07-18 四> 完成Desktop模块和程序关联和自动启动模块, 完成driver模块.
<2013-07-19 五> 完成程序关联模块，开始datetime模块,system_info模块
* 2
<2013-07-22 一> 个性化 线程池 pycurl 
<2013-07-23 二> pystorm 个性化完成 bug删除extra-wallpaper后 鼠标 触摸板
<2013-07-24 三> 开始蓝牙模块，上午看资料，下午修bug，实现蓝牙耳机连接电脑
<2013-07-25 四> 修复桌面通知删除所有记录会清空数据库的bug，找到蓝牙不能接受手机请求的bug，开始想办法修复之
* 3
<2013-07-29 一> 上午忙活蓝牙。看关于键盘的设置，看不懂，后转为看power，完成。
<2013-07-30 二> 上午键盘+培训，下午培训
<2013-07-31 三> 培训
<2013-08-01 四> 上午看键盘，下午修bug，autostart错误格式文件导致系统设置挂掉
<2013-08-02 五> 继续键盘模块的学习，修复系统托盘农历信息显示时间太短的bug，添加低电量提醒的功能。
* 4
<2013-08-05 一> 蓝牙作为输入端 个性化下载失败不能下载的问题 新通知默认不刷新bug 
<2013-08-06 二> 尝试为蓝牙设置总的agent以实现其他设备主动连接deepin的功能，但是与trayicon的mainloop冲突，失败，暂时搁置，实现蓝牙听歌等
<2013-08-07 三> 根据设备提供的服务动态生成菜单，不再是单一的发送文件。增加正在搜索的动画。
<2013-08-08 四> 上午能实现接受文件，但是没有进度提示和完成提示。修复系统设置不能实时展示设置后端改变的bug，
                修复从某个模块返回到导航页面后使用命令不能返回到模块的bug，修复通知action点击没有反应的bug。
<2013-08-09 五> 添加进度提示和成功失败提示。修复bug libnotify产生的action点击无效。
* 5
<2013-08-12 一> 新建进程执行一些后台服务， 发送notification失败
<2013-08-13 二> 上午实现InputDialog阻塞函数执行，实现了蓝牙输入pin码连接。对话框的形式实现了是否接受文件传输。实现托盘的菜单自动选择。
<2013-08-14 三> 上午折腾dialog阻塞执行。尝试以带timeout的raw_input实现阻塞，失败。下午跟xiangzhai一块研究，尝试加入__is_reject实现，
                不行。找到开机启动项没有中文描述的原因。
<2013-08-15 四> 尝试以原生gtk的界面实现，成功。尝试原生gtk与新的共存，失败。彻底修复系统设置页面跳转失败的bug，继承gtk.Dailog实现自己的对话框。
<2013-08-16 五> 不在使用自己的实现，将module_frame中的threads_init在蓝牙模块禁用。修复搜索中的bug，修复错误出现时窗口移动到别处的bug。
                修复蓝牙不需要匹配即可连接的超级bug。
* 6
  <2013-08-19 一> 上午学习查找python内存泄漏的方法，修复桌面通知占用内存太多的bug。
                  下午尝试查找treeview的内存泄漏原因。
  <2013-08-20 二> 上午修复移除蓝牙adapter以后界面的蓝牙设备图标不会自动消失的bug，完成蓝牙的国际化。
                  下午修复其他蓝牙主动与系统蓝牙配对以后蓝牙设备界面不会自动刷新的bug，
                  修复托盘mount_media菜单界面崩溃（插入u盘立马拔出）。
  <2013-08-21 三> 修复mount_media托盘不会自动出现的bug。修复桌面设置左上角区域无法选择"打开的窗口"的bug。系统主题 grub
  <2013-08-22 四> 修复bug点击网络壁纸会先设置壁纸为系统默认壁纸。修复bug 重启蓝牙服务后托盘卡死。

* 7
  <2013-08-26 一> 修缮原来的写好的关于修改grub的api，搭建好使用dbus提权的框架，测试通过。
  <2013-08-27 二> 测试蓝牙的相关功能， 决定如何修改grub配置文件。完成界面配置写入配置文件。
  <2013-08-28 三> 修复蓝牙服务不自动重启导致托盘点击无反应的bug。看grub manual文档寻找更好的修改启动想顺序的办法,完成预览功能。
  <2013-08-29 四> 修复英文版系统设置不能搜索的bug，查询如何设置打字时禁用键盘，查找资料如何加入硬盘standby和wakeup的模式。耳麦单击信号尝试
  <2013-08-30 五> 继续昨天未完成的蓝牙单击信号任务，终于找到耳机触发的方式，中间琢磨dbus接收信号的问题，收获颇多。完成grub菜单设置相关动作（上下移动，重命名，删除）的动作。
                  尝试完成grub设置完整的流程。
